server:
  port: 8085

spring:
  application:
    name: match-service
  liquibase:
    change-log: classpath:db/changelog/betting-changelog-master.yaml

  redis:
    host: localhost
    port: :6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  datasource:
    url: jdbc:postgresql://localhost:5436/betting_matches
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Match service specific configurations
match:
  schedule:
    update-interval: 300000 # 5 minutes
  external-api:
    timeout: 10000 # 10 seconds
    retry-attempts: 3
logging:
  level:
    betting_platform: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    root: INFO
