server:
  port: 8084

spring:
  application:
    name: odds-service

  liquibase:
    change-log: classpath:db/changelog/betting-changelog-master.yaml

    kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: odds-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      

  datasource:
    url: jdbc:postgresql://localhost:5437/betting_platform
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true  # ✅ Cho phép override bean nếu cần

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

match:
  schedule:
    update-interval: 300000 # 5 minutes
  external-api:
    timeout: 10000 # 10 seconds
    retry-attempts: 3

logging:
  level:
    betting_platform: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    root: INFO
