server:
  port: 8082

spring:
  application:
    name: wallet-service
  liquibase:
    change-log: classpath:db/changelog/betting-changelog-master.yaml
  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      group-id: wallet-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true  # Bật auto commit
      auto-commit-interval: 1000  # Commit mỗi 1 giây
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    url: jdbc:postgresql://localhost:5434/betting_platform
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    betting_platform: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    root: INFO
